---
title: "Climate issue voting"
author: "Malo Jan"
---

Is there a climate issue voting ? Do climate change play a role in electoral competition and voting choice ? For whom and under which circumstances ? 

As climate change become an increasing urgent problem, it is important to understand how it becomes politicize. As important changes requires political majorities to support this changes, election play a role in giving a mandate to political actors to change. The question is so, how people engage politically to make that change happens, and does this have any effects on policy outcomes at the end. A parallel question is whether or not it benefits to the greens or not. While we see that climate change is increasingly salient in the public debate, electoral change is not really here, and majorities are not given to support it, greens progress but not that much even in elections where the topic was really salient such as in Norway (see Farstad on the questions), or in Germany. 

Our general guess is rather than we do not observe climate issue voting and this is puzzling as such and we want to understand why. And under which circumstances it appears. 

One of the reasons the greens do not benefit necesarrily for the raising of green salience is that first : 

- Their ownership is contested by other parties, in particular from the left
- The competition is increasingly positional and so more and different positions rather than on competence

# What is issue voting

# The conditions of climate issue voting

- Stokes and Butler : salience of the issue, divisions of the public, opposition among parties

- It could be that the absence of
- Polarisation is a necessary condition of issue voting -Sciarni Kriesi 2003, Rovnt 2012
- Ideological convergence between parties increases issue voting (Green, Hobolt 2008, Bélanger and Meguid 2008)

# How to measure issue voting

