---
title: "comparative_climate_policy"
---

Why do countries differ in the climate policies they implement ? What can be compared and how can we explain the different instruments they choose ? Their different performances ? 

# Why compare countries ? 

- A collective action problem and international politics
- But lot of variation

# What is to be compared ? 

The first difficulty when we want to compare climate policies across countries is what exactly is our dependent variable : what is to be compared ? Climate change is a really complex problem many different variables have been used, each of them having big limits. 


The first possibility is to measure **GHG emissions**, which are the main drivers of climate change. 

- How they act on international arena : see phd Genovese, Climate cooperation index, when do they ratify

Rather than **policy outcomes**, other studies have tried to measure **policy outputs** such as the number of climate laws or policies. This have been developed following attempts to build datasets of climate laws such as the Climate Laws of the Worls. The leading authors then look at the factors of climate legislation adoption. 

More recently, following the Paris Agreement, scholars and Ngos have started to compare the NDCs, the pledges that countries have proposed. It is possible to compare their **ambitiousness** regarding emissions reduction but then also how countries keep tracks on their pledges. This is often done in a goal to same and shame and to make governments accountable for climate policies. 

It is also possible to compare their institutions of climate governance, what they have build and so on

# Political Economy perspectives

A first perspective to explain diverging performance

# Institutional accounts

- Political regimes
- Electoral systems
- State size
- Interest-group representations

## Political Parties

- Political parties : left vs right, influence of greens or even radical right parties
- See Tobin with QCA and Lockwood and Lockwood
- Spoon et al : testing matter hypothesis on Kyoto

- Do the importance of green parties in some countries affect the public concern of climate change in that country ? The performance of that country ? Is importance measured by their vote share, their number of seats in parliament or they importance in governement ? It could be possible to estimate ths on climate performance with QCA or polled-panel data with the climate policy performance index de German Watch.  


- Radical Right parties have negative effects on climate policies : 

Our key findings, which are robust to a set of other political, economic and environmental controls, are, first, that RWPPs do have a significant negative impact on climate policy, but not on renewable energy policy; second, that the impact of RWPPs on climate policy is mitigated by proportional representation (PR) and by membership of the EU; and third, that climate policy effects of RWPPs in majoritarian countries work via both executive and legislative channels » (Lockwood et Lockwood, 2022, p. 13)